### ISSUE TITLE
Include a ready to use yarr site

### ISSUE THREAD

**Issue by avoine** [radiac/django-yarr#45]
What would you think about adding adding an example directory with a basic django project
with the settings, urls and templates configured for yarr?
That would make it easier for people to try your application without having any knowledge about
Django.

**Comment by twm** [comment]
This would make it much easier to contribute.  I ended up tweaking some settings and replacing the stock CSS entirely for my own site, so it's difficult to know if changes I make break anything in a less-custom site.
